version: "3.3"
services:
  traefik:
    image: "traefik:${VERSION}"
    container_name: "traefik"
    command:
      # - "--log.level=${LOG}"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=${PROVIDER}"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=${RESOLVER}"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" #For testing
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    environment: 
      - TZ
      - CF_DNS_API_TOKEN
      - CF_ZONE_API_TOKEN
      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
      - "./traefik.yml:/traefik/traefik.yml"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.rule=Host(`speedtest.onelumen.co.uk`)"

# services:
#   traefik:
#     image: traefik:${VERSION}
#     container_name: traefik
#     command:
#       - --log.level=DEBUG
#       - --api.insecure=true 
#       - --providers.docker=true 
#       - --providers.docker.exposedbydefault=false 
#       - --log.level=${LOG}
#       - --entrypoints.http.address=:80 
#       - --entrypoints.https.address=:443
#       # cert resolver
#       - --certificatesresolvers.myresolver.acme.dnschallenge=true
#       - --certificatesresolvers.${PROVIDER}.acme.dnschallenge.provider=${PROVIDER}
#       - --certificatesresolvers.${PROVIDER}.acme.dnschallenge.delayBeforeCheck=0
#       - --certificatesresolvers.${PROVIDER}.acme.dnschallenge.resolvers=${RESOLVER}
#       - --certificatesresolvers.${PROVIDER}.acme.email=${EMAIL}
#       - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
#     environment: 
#       - TZ
#       - AWS_ACCESS_KEY_ID
#       - AWS_REGION
#       - AWS_SECRET_ACCESS_KEY
#       - AWS_HOSTED_ZONE_ID
#     ports:
#       - "443:443"
#       - "80:8080"
#     volumes:
#       - letsencrypt:/letsencrypt
#       - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  letsencrypt: