################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
################################################################
# Challenge DNS
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: ${EMAIL}
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: route53
        delayBeforeCheck: 0
################################################################
# Traefik Logging
################################################################
log:
  level: INFO